name: 'user-srv'
mysql:
  host: '148.70.50.244'
  port: 3306
  user: 'root'
  password: 'Qwe,123'
  db: 'mxshop_user_srv'

consul:
  host: '148.70.50.244'
  port: 8500


host: '1.14.105.109'
tags: ["imooc", "bobby", "user", "srv"]
port: 8848
namespace: 'e949a60d-1266-4663-9b53-9ca370d18fbd'
user: 'nacos'
password: 'nacos'
dataid: 'goods-grpc.json'
group: 'dev'