name: 'user-srv'
mysql:
  host: '148.70.50.244'
  port: 3306
  user: 'root'
  password: 'Qwe,123'
  db: 'mxshop_user_srv'

consul:
  host: '148.70.50.244'
  port: 8500


host: '1.14.105.109'
port: 8848
namespace: 'c31a770d-dc94-4d55-905a-9d26b5a72402'
user: 'nacos'
password: 'nacos'
dataid: 'user-grpc.json'
group: 'dev'