name: 'order-srv'
mysql:
  host: '148.70.50.244'
  port: 3306
  user: 'root'
  password: 'Qwe,123'
  db: 'mxshop_order_srv'

consul:
  host: '148.70.50.244'
  port: 8500


host: '1.14.105.109'
tags: ["imooc", "bobby", "order", "srv"]
port: 8848
namespace: '0efc9199-6099-4954-ae64-1fc83e61f0f2'
user: 'nacos'
password: 'nacos'
dataid: 'order-grpc.json'
group: 'dev'