user_srv:
  host: '127.0.0.1'
  port: 50051
  name: 'usr-srv'


jwt:
  key: 'asdasdqrrq@432'

sms:
  key: ''
  secret: ''

redis:
  host: '127.0.0.1'
  port: 6379

consul:
  host: '148.70.50.244'
  port: 8500


host: '1.14.105.109'
port: 8848
namespace: 'c31a770d-dc94-4d55-905a-9d26b5a72402'
user: 'nacos'
password: 'nacos'
dataid: 'user-web.json'
group: 'dev'